S03 t04 all nav
WildCodeSchool/0923-lille-js-makesense pull request #2
Opened 2023-12-20 09:10 UTC by FlorenceBuchelet

nav bar for all pages (minus login)

2023-12-20 09:28 UTC, HeleneRamp approved these changes

2023-12-20 10:20 UTC, Sax593 requested changes

2023-12-20 10:20 UTC, Sax593 commented on frontend/src/_variables.scss
> +@import "./variables";
death code

2023-12-20 10:24 UTC, FlorenceBuchelet commented on frontend/src/_variables.scss
> +@import "./variables";
C'est la ligne matrice à copier-coller sur chaque fichier scss, elle est volontairement commentée pour être facilement accéssible.

2023-12-20 16:03 UTC, FlorenceBuchelet commented on frontend/src/_variables.scss
> +@import "./variables";
C'est tout bon !

2023-12-21 08:19 UTC, Sax593 approved these changes

2023-12-21 08:40 UTC, HeleneRamp approved these changes

2023-12-21 08:41 UTC, merged