S03 t02 login
WildCodeSchool/0923-lille-js-makesense pull request #3
Opened 2023-12-20 14:16 UTC by Farid-Zian

2023-12-20 16:09 UTC, Sax593 requested changes

2023-12-20 16:09 UTC, Sax593 commented on frontend/src/pages/login.jsx
> +        <label className="identify">
missing htmlfor

2023-12-20 16:09 UTC, Sax593 commented on frontend/src/pages/login.jsx
> +          <input type="text" />
missing id and name

2023-12-20 16:09 UTC, Sax593 commented on frontend/src/pages/login.jsx
> +        <label className="password">
same

2023-12-20 16:09 UTC, Sax593 commented on frontend/src/pages/login.jsx
> +          <input type="password" />
same

2023-12-20 16:14 UTC, FlorenceBuchelet requested changes

2023-12-20 16:14 UTC, FlorenceBuchelet commented on frontend/src/assets/image/r_background-image.png
asset non utilisé ?

2023-12-20 16:14 UTC, FlorenceBuchelet commented on frontend/src/pages/login.jsx
Revoir les classNames en BEM

2023-12-20 16:14 UTC, FlorenceBuchelet commented on frontend/src/pages/login.jsx
> +    <div className="content">
className="login__content"

2023-12-20 16:14 UTC, FlorenceBuchelet commented on frontend/src/pages/login.jsx
> +        className="logo"
className="login__logo"

2023-12-20 16:14 UTC, FlorenceBuchelet commented on frontend/src/pages/login.jsx
> +      <form>
className="login__form"

2023-12-20 16:14 UTC, FlorenceBuchelet commented on frontend/src/pages/login.jsx
> +        <label className="identify">
className="login__form--identify"

2023-12-20 16:14 UTC, FlorenceBuchelet commented on frontend/src/pages/login.jsx
> +        <br />
Tester flex plutôt que des br

2023-12-20 16:14 UTC, FlorenceBuchelet commented on frontend/src/pages/login.jsx
> +        <label className="password">
className="login__form--password"

2023-12-20 16:14 UTC, FlorenceBuchelet commented on frontend/src/pages/login.jsx
> +        <button className="button-connect" type="submit">
className="login__form--buttonConnect"

2023-12-20 16:14 UTC, FlorenceBuchelet commented on frontend/src/pages/login.scss
Mettre à jour les className

2023-12-26 20:34 UTC, FlorenceBuchelet commented
Il faut que tu edit Login sur cette branche pour pouvoir push à nouveau et mettre à jour la PR.

2024-01-03 14:01 UTC, FlorenceBuchelet approved these changes

2024-01-03 14:41 UTC, fantinerudent approved these changes

2024-01-03 15:04 UTC, Sax593 approved these changes

2024-01-03 15:05 UTC, merged